// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRvcae66AI_5_8989uSBrzw5XYfI7_bzk',
    appId: '1:295469782919:web:9a9f2683517ce59087e522',
    messagingSenderId: '295469782919',
    projectId: 'newapp-a5ee7',
    authDomain: 'newapp-a5ee7.firebaseapp.com',
    storageBucket: 'newapp-a5ee7.appspot.com',
    measurementId: 'G-GX7V47CRFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRACz535MChDlDe3u2Fg1W2sfl9aWexjY',
    appId: '1:295469782919:android:1124a7ec6208779487e522',
    messagingSenderId: '295469782919',
    projectId: 'newapp-a5ee7',
    storageBucket: 'newapp-a5ee7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINqFDQnuzVDPuaa1LFkmcx3tsxgitxZY',
    appId: '1:295469782919:ios:44bd16db55e5c19c87e522',
    messagingSenderId: '295469782919',
    projectId: 'newapp-a5ee7',
    storageBucket: 'newapp-a5ee7.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBINqFDQnuzVDPuaa1LFkmcx3tsxgitxZY',
    appId: '1:295469782919:ios:597d2a5ef45c3f6987e522',
    messagingSenderId: '295469782919',
    projectId: 'newapp-a5ee7',
    storageBucket: 'newapp-a5ee7.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
